name: Publish package to GitHub Packages
on: [push]
jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: prebuild
        run: ./gradlew clean build
      - name: Disallow Concurrent Runs
        uses: byu-oit/github-action-disallow-concurrent-runs@v2
        with:
          token: ${{ github.token }}
      - name: Publish package
        run: ./gradlew --no-parallel publishAllPublicationsToGithubPackagesRepository
        env:
          GITHUBPACKAGES_USER: ${{ github.actor }}
          GITHUBPACKAGES_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          additional_version: "-build${{ github.run_number }}"
